### ISSUE TITLE
TypeError on npm start or node app.js

### ISSUE THREAD

**Issue by anoop0567** [zapier/node-resthooksdemo#4]
**Node Version : v10.16.0
Npm Version : 6.9.0**

**Error:**
`Store.prototype.__proto__ = EventEmitter.prototype;
`                                      
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/home/work/Downloads/rest-hooks/node_modules/socket.io/lib/store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/work/Downloads/rest-hooks/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)

**Comment by shasharm14** [comment]
any solution for this?

**Comment by anoop0567** [comment]
Not yet moving to zapier polling method.

**Comment by shasharm14** [comment]
thanks for replying, is it good option to use firebase db as a replacement of polling?

**Comment by anoop0567** [comment]
we manually wrote API for rest hook. On every new subscriber, zapier gives a hookUrl in which you have to push the data.
